### ISSUE TITLE
Allow the mint to generate different kinds of tokens

### ISSUE THREAD

**Issue by predfunction** [cashubtc/nuts#29]
Right now when a wallet requests keys, the mint returns keys for denominations of satoshis.  I'd like to be able to have a mint that can issue both satoshi tokens and, for example, "USD cent" tokens.

One way to do this would be to have different mints for each token kind, and wallets would just have to keep track of which mint issues which kind of token.  But there are some use cases when you might want many different kinds of tokens (for example, if you want the mint to back up some kind of trading market).

There may be a way to do this with the bitcoin scripting functionality, but since it is not documented, I'm not sure.

**Comment by callebtc** [comment]
This should be possible but it would require a bunch of backend work to be able to keep the USD balance in a backend. We don't have a clear idea yet how to bake multiple denominations into the protocol but using Cashu for _exclusively_ another denomination should be fairly straightforward once you have a stable balance to move around on LN. 

Closing since this is not specifically protocol-related and would need to be hashed out in one of the implementations.
