### ISSUE TITLE
Does Cashu support floating-point numbers?

### ISSUE THREAD

**Issue by shanelau** [cashubtc/nuts#43]
How can I send tokens in smaller units, like 1.234 sats?

When I input a float amount, the website https://wallet.cashu.me/ shows a 500 error. Does Cashu support float numbers? 

Or support  millisatoshi

<img width="724" alt="image" src="https://github.com/cashubtc/nuts/assets/3140898/f893b3f3-f752-4557-ba61-e9abdca931c2">

**Comment by AngusP** [comment]
No, at the moment the `amount`s are all integers ([NUT00](https://github.com/cashubtc/nuts/blob/main/00.md)) and in [reference implementation](https://github.com/cashubtc/cashu/blob/0a5beb75a219f30112ee510d613c70ffde653e06/cashu/mint/migrations.py#L19) schema, they're integers.

That being said, amount of *what* isn't specified, but implementation consensus is it's satoshis. So you could run a mint where the denomination (`amount = 1`) is millisats, but you'd need to tweak the mint implementation, and then most clients/wallets would assume it's sats not msats.

Floats for money are generally a bad idea because you hit problems around loss of and varying precision, like `0.1 + 0.2 != 0.3` (try it!), but it would perhaps be sensible for mints to be able to specify what their base denomination is (bits, **sats**, msats, or even µsats?)

**Comment by shanelau** [comment]
Based on our business, we do need an implementation in units of msats, When transferring into the Lightning Network, the user will receive 1000 msats for 1 sat .

If BTC rises to $1 million., the price of 1sats will also be expensive.

As for the issue of decimal calculations, I believe bigNumber can solve it.

The server-side needs configurable units: sats, msats, usats.

**Comment by shanelau** [comment]
Yes, it is workable for a long time. But not the best choice.
